train_folders:
  - "/lustre/orion/csc590/proj-shared/math-adder/merged-symbols/train"
eval_folders: []
base_dir: "/lustre/orion/csc590/scratch/jonathanlimsc/bgpt/testrun"
weights_path: "weights.pth"
pre_weights_path: null
logs_path: "log.txt"
checkpoint_path: "checkpoints"
dataloader_path: "dataloaders"
patch_size: 16
patch_length: 512
byte_num_layers: 3
patch_num_layers: 24
hidden_size: 1024
num_epochs: 5
learning_rate: 0.0001
batch_size: 8
accumulation_steps: 1
patch_sampling_batch_size: 0
load_from_checkpoint: false
load_from_pre_checkpoint: false
checkpoint_frequency: 5
first_launch: true
verbose: false
wandb:
  proj_name: byte_models
  entity: jonathanlimsc
  mode: offline
