train_folders:
  - "/network/scratch/m/mina.beiramy/bgpt_shared/image_mnist/train"
eval_folders:
  - "/network/scratch/m/mina.beiramy/bgpt_shared/image_mnist/validation"
base_dir: "/network/scratch/m/mina.beiramy/bgpt_shared/models/multimodal-mnist-image-cls-ft"
weights_path: "weights.pth"
pre_weights_path: "/network/scratch/m/mina.beiramy/bgpt_shared/models/multimodal-mnist-gen/checkpoints/latest.pth"
logs_path: "log.txt"
checkpoint_path: "checkpoints"
dataloader_path: "dataloaders"
patch_size: 16
patch_length: 512
byte_num_layers: 3
patch_num_layers: 12
hidden_size: 768
num_epochs: 20
learning_rate: 0.00001
batch_size: 1
patch_sampling_batch_size: 0
load_from_pre_checkpoint: true
logging_frequency: 500
first_launch: true
verbose: false
wandb:
  proj_name: byte_models
  entity: jonathanlimsc-wandb
  mode: online # put 'offline' if you don't want it to upload to WanB server
  name: multimodal-mnist-image-cls-ft