train_folders:
  - "/network/scratch/m/mina.beiramy/bgpt_shared/audio-mnist/train_r"
eval_folders:
  - "/network/scratch/m/mina.beiramy/bgpt_shared/audio-mnist/val_r"
base_dir: "/network/scratch/m/mina.beiramy/bgpt_shared/models/multimodal-mnist-audio-cls-ft-small"
weights_path: "weights.pth"
pre_weights_path: "/network/scratch/m/mina.beiramy/bgpt_shared/models/multimodal-mnist-gen-small/checkpoints/latest.pth"
logs_path: "log.txt"
checkpoint_path: "checkpoints"
dataloader_path: "dataloaders"
patch_size: 16
patch_length: 512
byte_num_layers: 2
patch_num_layers: 6
hidden_size: 256
num_epochs: 20
learning_rate: 0.00001
batch_size: 1
patch_sampling_batch_size: 0
load_from_pre_checkpoint: true
logging_frequency: 500
first_launch: true
verbose: false
wandb:
  proj_name: byte_models
  entity: jonathanlimsc-wandb
  mode: online # put 'offline' if you don't want it to upload to WanB server
  name: multimodal-mnist-audio-cls-ft-small