train_folders:
  - "/network/scratch/m/mina.beiramy/bgpt_shared/image_mnist/train"
  - "/network/scratch/m/mina.beiramy/bgpt_shared/image_mnist/validation"
  - "/network/scratch/m/mina.beiramy/bgpt_shared/image_mnist/test"
  - "/network/scratch/m/mina.beiramy/bgpt_shared/audio-mnist/train_r"
  - "/network/scratch/m/mina.beiramy/bgpt_shared/audio-mnist/val_r"
  - "/network/scratch/m/mina.beiramy/bgpt_shared/audio-mnist/test_r"
eval_folders: []
base_dir: "/network/scratch/m/mina.beiramy/bgpt_shared/models/multimodal-mnist-gen-small"
weights_path: "weights.pth"
pre_weights_path: null
logs_path: "log.txt"
checkpoint_path: "checkpoints"
dataloader_path: "dataloaders"
patch_size: 16
patch_length: 512
byte_num_layers: 2
patch_num_layers: 6
hidden_size: 256
num_epochs: 50
learning_rate: 0.0001
batch_size: 26
accumulation_steps: 1
patch_sampling_batch_size: 0
load_from_pre_checkpoint: false
checkpoint_frequency: 2000
logging_frequency: 500
first_launch: true
verbose: false
wandb:
  proj_name: byte_models
  entity: jonathanlimsc-wandb
  mode: online # put 'offline' if you don't want it to upload to WanB server
  name: multimodal-mnist-gen-small