train_folders:
  - "/lustre/orion/csc590/proj-shared/math-adder/merged-symbols/sample_10K"
  # - "/lustre/orion/csc590/proj-shared/math-adder/merged-symbols/train"
  # - "/lustre/orion/csc590/proj-shared/mathematics_dataset-v1.0/train-easy"
  # - "/lustre/orion/csc590/proj-shared/mathematics_dataset-v1.0/train-medium"
  # - "/lustre/orion/csc590/proj-shared/mathematics_dataset-v1.0/train-hard"
  # - "/lustre/orion/csc590/proj-shared/wikipedia/train_text3"
  # - "/lustre/orion/csc590/proj-shared/imagenet-1k/train"
eval_folders: []
base_dir: "/lustre/orion/csc590/scratch/jonathanlimsc/bgpt/test_continual"
weights_path: "weights.pth"
pre_weights_path: null
logs_path: "log.txt"
checkpoint_path: "checkpoints"
dataloader_path: "dataloaders"
patch_size: 16
patch_length: 512
byte_num_layers: 3
patch_num_layers: 12
hidden_size: 768
num_epochs: 32
learning_rate: 0.0001
batch_size: 16
accumulation_steps: 1
patch_sampling_batch_size: 0
# load_from_checkpoint: false # Deprecated this into a command-line arg that is False by default. So that there's no need to maintain a config where this is True and a reload config where this is True.
load_from_pre_checkpoint: false
checkpoint_frequency: 40
first_launch: true
verbose: false
wandb:
  proj_name: byte_models
  entity: jonathanlimsc
  mode: offline
